version: '3.1'
services:

  db:
    image: postgres
    container_name: db_react_query
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root